/*
Variable Labels for Penn World Tables - http://www.rug.nl/ggdc/productivity/pwt/
*/

label var country	"Country name"
label var currency_unit	"Currency unit"
label var year	"Year"
label var rgdpe	"Expenditure-side real GDP at chained PPPs (in mil. 2011US$)"
label var rgdpo	"Output-side real GDP at chained PPPs (in mil. 2011US$)"
label var pop	"Population (in millions)"
label var emp	"Number of persons engaged (in millions)"
label var avh	"Average annual hours worked by persons engaged"
label var hc	"Human capital index, based on years of schooling and returns to education; see Human capital in PWT9."
label var ccon	"Real consumption of households and government, at current PPPs (in mil. 2011US$)"
label var cda	"Real domestic absorption, (real consumption plus investment), at current PPPs (in mil. 2011US$)"
label var cgdpe	"Expenditure-side real GDP at current PPPs (in mil. 2011US$)"
label var cgdpo	"Output-side real GDP at current PPPs (in mil. 2011US$)"
label var ck	"Capital stock at current PPPs (in mil. 2011US$)"
label var ctfp	"TFP level at current PPPs (USA=1)"
label var cwtfp	"Welfare-relevant TFP levels at current PPPs (USA=1)"

label var rgdpna	"Real GDP at constant 2011 national prices (in mil. 2011US$)"
label var rconna	"Real consumption at constant 2011 national prices (in mil. 2011US$)"
label var rdana	"Real domestic absorption at constant 2011 national prices (in mil. 2011US$)"
label var rkna	"Capital stock at constant 2011 national prices (in mil. 2011US$)"
label var rtfpna	"TFP at constant national prices (2011=1)"
label var rwtfpna	"Welfare-relevant TFP at constant national prices (2011=1)"
label var labsh	"Share of labour compensation in GDP at current national prices"
label var delta	"Average depreciation rate of the capital stock"

label var xr	"Exchange rate, national currency/USD (market+estimated)"
label var pl_con	"Price level of CCON (PPP/XR), price level of USA GDPo in 2011=1"
label var pl_da	"Price level of CDA (PPP/XR), price level of USA GDPo in 2011=1"
label var pl_gdpo	"Price level of CGDPo (PPP/XR),  price level of USA GDPo in 2011=1"

label var i_cig	"0/1/2: relative price data for consumption, investment and government is extrapolated (0), benchmark (1) or interpolated (2)"
label var i_xm	"0/1/2: relative price data for exports and imports is extrapolated (0), benchmark (1) or interpolated (2)"
label var i_xr	"0/1: the exchange rate is market-based (0) or estimated (1)"
label var i_outlier	"0/1: the observation on pl_gdpe or pl_gdpo is not an outlier (0) or an outlier (1)"
label var cor_exp	"Correlation between expenditure shares of the country and the US (benchmark observations only)"
label var statcap	"Statistical capacity indicator (source: World Bank, developing countries only)"

label var csh_c	"Share of household consumption at current PPPs"
label var csh_i	"Share of gross capital formation at current PPPs"
label var csh_g	"Share of government consumption at current PPPs"
label var csh_x	"Share of merchandise exports at current PPPs"
label var csh_m	"Share of merchandise imports at current PPPs"
label var csh_r	"Share of residual trade and GDP statistical discrepancy at current PPPs"

label var pl_c	"Price level of household consumption,  price level of USA GDPo in 2011=1"
label var pl_i	"Price level of capital formation,  price level of USA GDPo in 2011=1"
label var pl_g	"Price level of government consumption,  price level of USA GDPo in 2011=1"
label var pl_x	"Price level of exports, price level of USA GDPo in 2011=1"
label var pl_m	"Price level of imports, price level of USA GDPo in 2011=1"
label var pl_k	"Price level of the capital stock, price level of USA in 2011=1"
